# Generated by Django 5.2.12 on 2026-03-18 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Ano')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Mês')),
                ('status', models.CharField(choices=[('open', 'Aberto'), ('submitted', 'Enviado'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('overdue', 'Em atraso')], default='open', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado em')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Revisado em')),
                ('manager_notes', models.TextField(blank=True, verbose_name='Observações do gestor')),
                ('participant_notes', models.TextField(blank=True, verbose_name='Observações do participante')),
                ('declaration_no_movement', models.BooleanField(default=False, verbose_name='Sem movimentação')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participants.participant')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_closings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month', 'participant__trade_name'],
                'unique_together': {('participant', 'year', 'month')},
            },
        ),
    ]
