# Generated by Django 5.2.12 on 2026-04-16 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0004_fix_manager_notes'),
        ('participants', '0005_remove_participant_part_org_status_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlyclosing',
            options={'ordering': ['-year', '-month'], 'verbose_name': 'Fechamento Mensal', 'verbose_name_plural': 'Fechamentos Mensais'},
        ),
        migrations.AlterField(
            model_name='monthlyclosing',
            name='manager_notes',
            field=models.TextField(blank=True, default='', verbose_name='Observações do gestor'),
        ),
        migrations.AlterField(
            model_name='monthlyclosing',
            name='month',
            field=models.PositiveIntegerField(verbose_name='Mês'),
        ),
        migrations.AlterField(
            model_name='monthlyclosing',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_closings', to='participants.participant'),
        ),
        migrations.AlterField(
            model_name='monthlyclosing',
            name='participant_notes',
            field=models.TextField(blank=True, default='', verbose_name='Observações do participante'),
        ),
        migrations.AlterField(
            model_name='monthlyclosing',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo da rejeição'),
        ),
        migrations.AlterField(
            model_name='monthlyclosing',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Revisado em'),
        ),
        migrations.AlterField(
            model_name='monthlyclosing',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_closings', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por'),
        ),
        migrations.AlterField(
            model_name='monthlyclosing',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Enviado em'),
        ),
    ]
