from django.urls import path
from .views import (
    EntryCreateView, EntryListView, EntryUpdateView,
    SaleCreateView, SaleListView, SaleUpdateView,
    TransformationCreateView, TransformationListView, TransformationUpdateView,
    DocumentCenterView,
    DataManagementView, DataDeleteView, DataDeleteSingleView,
    BillingReportView, BillingTierUpdateView,
    parse_nfe_view,
    NfeLoteView, parse_nfe_lote_view, importar_nfe_lote_view,
    exportar_saldo_csv,
)

urlpatterns = [
    path('entries/', EntryListView.as_view(), name='entry_list'),
    path('entries/new/', EntryCreateView.as_view(), name='entry_create'),
    path('entries/<int:pk>/edit/', EntryUpdateView.as_view(), name='entry_update'),
    path('sales/', SaleListView.as_view(), name='sale_list'),
    path('sales/new/', SaleCreateView.as_view(), name='sale_create'),
    path('sales/<int:pk>/edit/', SaleUpdateView.as_view(), name='sale_update'),
    path('transformations/', TransformationListView.as_view(), name='transformation_list'),
    path('transformations/new/', TransformationCreateView.as_view(), name='transformation_create'),
    path('transformations/<int:pk>/edit/', TransformationUpdateView.as_view(), name='transformation_update'),
    path('documents/', DocumentCenterView.as_view(), name='document_center'),
    path('gestor/dados/', DataManagementView.as_view(), name='data_management'),
    path('gestor/dados/excluir/', DataDeleteView.as_view(), name='data_delete'),
    path('gestor/dados/excluir/unico/', DataDeleteSingleView.as_view(), name='data_delete_single'),
    path('gestor/faturamento/', BillingReportView.as_view(), name='billing_report'),
    path('gestor/faturamento/salvar/', BillingTierUpdateView.as_view(), name='billing_tier_update'),
    path('nfe/parse/', parse_nfe_view, name='nfe_parse'),
    path('nfe/lote/', NfeLoteView.as_view(), name='nfe_lote'),
    path('nfe/lote/parse/', parse_nfe_lote_view, name='nfe_parse_lote'),
    path('nfe/lote/importar/', importar_nfe_lote_view, name='nfe_importar_lote'),
    path('saldo/exportar/', exportar_saldo_csv, name='exportar_saldo_csv'),
]
