# Generated by Django 5.2.15 on 2026-06-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_bootstrap_participant_users'),
        ('participants', '0007_participant_ativo_coc_participant_ativo_fm'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='participantes_manejo',
            field=models.ManyToManyField(blank=True, help_text='Permite que este usuário gerencie Manejo Florestal de mais de um participante. Não se aplica ao módulo de Cadeia de Custódia.', related_name='usuarios_manejo', to='participants.participant', verbose_name='Participantes adicionais (Manejo Florestal)'),
        ),
    ]
