# Generated by Django 5.2.12 on 2026-03-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=255, verbose_name='Razão social')),
                ('trade_name', models.CharField(blank=True, max_length=255, verbose_name='Nome fantasia')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('contact_name', models.CharField(blank=True, max_length=255, verbose_name='Responsável')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('contact_phone', models.CharField(blank=True, max_length=30, verbose_name='Telefone')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo'), ('suspended', 'Suspenso')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['trade_name', 'legal_name'],
            },
        ),
    ]
