# Generated by Django 5.2.12 on 2026-03-26 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0004_participant_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='participant',
            name='part_org_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='participant',
            name='part_org_trade_idx',
        ),
    ]
