# Generated by Django 5.2.12 on 2026-06-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0006_bootstrap_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='ativo_coc',
            field=models.BooleanField(default=True, verbose_name='Cadeia de Custódia (CoC)'),
        ),
        migrations.AddField(
            model_name='participant',
            name='ativo_fm',
            field=models.BooleanField(default=False, verbose_name='Manejo Florestal (FM)'),
        ),
    ]
