# Generated by Django 5.2.12 on 2026-03-18 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('participants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_date', models.DateField(verbose_name='Data da movimentação')),
                ('document_number', models.CharField(max_length=50, verbose_name='Número do documento')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Quantidade')),
                ('unit_snapshot', models.CharField(max_length=10, verbose_name='Unidade')),
                ('fsc_claim', models.CharField(blank=True, max_length=100, verbose_name='Declaração FSC')),
                ('batch_code', models.CharField(blank=True, max_length=100, verbose_name='Lote')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('submitted', 'Enviado'), ('reviewed', 'Revisado'), ('needs_correction', 'Precisa correção')], default='draft', max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participants.participant')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='catalog.counterparty')),
            ],
            options={
                'ordering': ['-movement_date', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SaleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_date', models.DateField(verbose_name='Data da movimentação')),
                ('document_number', models.CharField(max_length=50, verbose_name='Número do documento')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Quantidade')),
                ('unit_snapshot', models.CharField(max_length=10, verbose_name='Unidade')),
                ('fsc_claim', models.CharField(blank=True, max_length=100, verbose_name='Declaração FSC')),
                ('batch_code', models.CharField(blank=True, max_length=100, verbose_name='Lote')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('submitted', 'Enviado'), ('reviewed', 'Revisado'), ('needs_correction', 'Precisa correção')], default='draft', max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='catalog.counterparty')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participants.participant')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
            ],
            options={
                'ordering': ['-movement_date', '-id'],
                'abstract': False,
            },
        ),
    ]
