# Generated by Django 5.2.12 on 2026-03-18 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_producttransformationrule_productunitconversion'),
        ('participants', '0001_initial'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entryrecord',
            name='movement_unit',
            field=models.CharField(blank=True, max_length=10, verbose_name='Unidade informada'),
        ),
        migrations.AddField(
            model_name='entryrecord',
            name='quantity_base',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Quantidade convertida (unidade base)'),
        ),
        migrations.AddField(
            model_name='salerecord',
            name='movement_unit',
            field=models.CharField(blank=True, max_length=10, verbose_name='Unidade informada'),
        ),
        migrations.AddField(
            model_name='salerecord',
            name='quantity_base',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Quantidade convertida (unidade base)'),
        ),
        migrations.AlterField(
            model_name='entryrecord',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Quantidade informada'),
        ),
        migrations.AlterField(
            model_name='entryrecord',
            name='unit_snapshot',
            field=models.CharField(max_length=10, verbose_name='Unidade base'),
        ),
        migrations.AlterField(
            model_name='salerecord',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Quantidade informada'),
        ),
        migrations.AlterField(
            model_name='salerecord',
            name='unit_snapshot',
            field=models.CharField(max_length=10, verbose_name='Unidade base'),
        ),
        migrations.CreateModel(
            name='TransformationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_date', models.DateField(verbose_name='Data da transformação')),
                ('source_quantity', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Quantidade origem')),
                ('source_unit', models.CharField(max_length=10, verbose_name='Unidade origem informada')),
                ('source_quantity_base', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Quantidade origem convertida')),
                ('target_quantity_base', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Quantidade destino gerada')),
                ('target_unit_snapshot', models.CharField(max_length=10, verbose_name='Unidade base destino')),
                ('yield_factor_snapshot', models.DecimalField(decimal_places=6, default=0, max_digits=14, verbose_name='Fator de rendimento aplicado')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='transformations/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participants.participant')),
                ('source_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transformations_as_source', to='catalog.product')),
                ('target_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transformations_as_target', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Transformação',
                'verbose_name_plural': 'Transformações',
                'ordering': ['-movement_date', '-id'],
            },
        ),
    ]
