# Generated by Django 5.2.12 on 2026-03-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_entryrecord_movement_unit_entryrecord_quantity_base_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryrecord',
            name='movement_unit',
            field=models.CharField(blank=True, choices=[('m3', 'm³'), ('kg', 'kg'), ('t', 't'), ('un', 'un')], max_length=10, verbose_name='Unidade informada'),
        ),
        migrations.AlterField(
            model_name='entryrecord',
            name='unit_snapshot',
            field=models.CharField(choices=[('m3', 'm³'), ('kg', 'kg'), ('t', 't'), ('un', 'un')], max_length=10, verbose_name='Unidade base'),
        ),
        migrations.AlterField(
            model_name='salerecord',
            name='movement_unit',
            field=models.CharField(blank=True, choices=[('m3', 'm³'), ('kg', 'kg'), ('t', 't'), ('un', 'un')], max_length=10, verbose_name='Unidade informada'),
        ),
        migrations.AlterField(
            model_name='salerecord',
            name='unit_snapshot',
            field=models.CharField(choices=[('m3', 'm³'), ('kg', 'kg'), ('t', 't'), ('un', 'un')], max_length=10, verbose_name='Unidade base'),
        ),
        migrations.AlterField(
            model_name='transformationrecord',
            name='source_unit',
            field=models.CharField(choices=[('m3', 'm³'), ('kg', 'kg'), ('t', 't'), ('un', 'un')], max_length=10, verbose_name='Unidade origem informada'),
        ),
        migrations.AlterField(
            model_name='transformationrecord',
            name='target_unit_snapshot',
            field=models.CharField(choices=[('m3', 'm³'), ('kg', 'kg'), ('t', 't'), ('un', 'un')], max_length=10, verbose_name='Unidade base destino'),
        ),
    ]
