# Generated by Django 5.2.12 on 2026-03-19 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_producttransformationrule_productunitconversion'),
        ('participants', '0001_initial'),
        ('transactions', '0003_alter_entryrecord_movement_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraceLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('entry', 'Entrada'), ('transformation', 'Transformação')], max_length=20)),
                ('movement_date', models.DateField(verbose_name='Data de origem')),
                ('quantity_base', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Quantidade do lote')),
                ('unit_snapshot', models.CharField(choices=[('m3', 'm³'), ('kg', 'kg'), ('t', 't'), ('un', 'un')], max_length=10, verbose_name='Unidade base')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trace_lot', to='transactions.entryrecord')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trace_lots', to='participants.participant')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trace_lots', to='catalog.product')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trace_lots', to='catalog.counterparty')),
                ('transformation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_trace_lot', to='transactions.transformationrecord')),
            ],
            options={
                'verbose_name': 'Lote rastreável',
                'verbose_name_plural': 'Lotes rastreáveis',
                'ordering': ['movement_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LotAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('sale', 'Saída'), ('transformation', 'Transformação')], max_length=20)),
                ('quantity_base', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Quantidade alocada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lot_allocations', to='participants.participant')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lot_allocations', to='transactions.salerecord')),
                ('transformation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_lot_allocations', to='transactions.transformationrecord')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='transactions.tracelot')),
            ],
            options={
                'verbose_name': 'Alocação de lote',
                'verbose_name_plural': 'Alocações de lotes',
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
