
# Generated by OpenAI on 2026-03-19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_producttransformationrule_participant'),
        ('transactions', '0006_salerecord_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='transformationrecord',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transformations_as_customer', to='catalog.counterparty', verbose_name='Cliente final'),
        ),
        migrations.AddField(
            model_name='transformationrecord',
            name='document_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Número do documento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transformationrecord',
            name='fsc_claim',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Declaração FSC'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transformationrecord',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transformations_as_source_supplier', to='catalog.counterparty', verbose_name='Fornecedor de origem'),
        ),
    ]
