# Generated by Django 5.2.12 on 2026-04-16 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_add_mst_unit'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='entryrecord',
            name='entry_part_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='entryrecord',
            name='entry_part_stat_dt_idx',
        ),
        migrations.RemoveIndex(
            model_name='entryrecord',
            name='entry_prod_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='entryrecord',
            name='entry_supp_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='lotallocation',
            name='alloc_part_tgt_idx',
        ),
        migrations.RemoveIndex(
            model_name='lotallocation',
            name='alloc_lot_tgt_idx',
        ),
        migrations.RemoveIndex(
            model_name='lotallocation',
            name='alloc_sale_idx',
        ),
        migrations.RemoveIndex(
            model_name='lotallocation',
            name='alloc_trf_idx',
        ),
        migrations.RemoveIndex(
            model_name='lotallocation',
            name='txn_alloc_part_lot_target_idx',
        ),
        migrations.RemoveIndex(
            model_name='salerecord',
            name='sale_part_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='salerecord',
            name='sale_part_stat_dt_idx',
        ),
        migrations.RemoveIndex(
            model_name='salerecord',
            name='sale_prod_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='salerecord',
            name='sale_cust_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='salerecord',
            name='sale_supp_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='tracelot',
            name='lot_part_src_dt_idx',
        ),
        migrations.RemoveIndex(
            model_name='tracelot',
            name='lot_part_prod_dt_idx',
        ),
        migrations.RemoveIndex(
            model_name='tracelot',
            name='lot_supp_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='tracelot',
            name='txn_lot_part_prod_av_idx',
        ),
        migrations.RemoveIndex(
            model_name='transformationrecord',
            name='trf_part_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='transformationrecord',
            name='trf_src_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='transformationrecord',
            name='trf_tgt_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='transformationrecord',
            name='trf_cust_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='transformationrecord',
            name='trf_supp_date_idx',
        ),
    ]
