# Generated by Django 5.2.12 on 2026-03-26 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_importjob'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='importjob',
            new_name='reports_imp_status_f8132f_idx',
            old_name='reports_impo_status_0d3221_idx',
        ),
        migrations.RenameIndex(
            model_name='importjob',
            new_name='reports_imp_partici_378f2d_idx',
            old_name='reports_impo_partici_858c85_idx',
        ),
        migrations.RenameIndex(
            model_name='importjob',
            new_name='reports_imp_created_fbd70a_idx',
            old_name='reports_impo_created_721566_idx',
        ),
    ]
