# Generated by Django 5.2.12 on 2026-03-18 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Produto')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Categoria')),
                ('unit', models.CharField(choices=[('m3', 'm³'), ('kg', 'kg'), ('t', 't'), ('un', 'un')], max_length=10, verbose_name='Unidade')),
                ('fsc_applicable', models.BooleanField(default=True, verbose_name='Aplica FSC')),
                ('default_claim', models.CharField(blank=True, max_length=100, verbose_name='Declaração padrão')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('document_id', models.CharField(blank=True, max_length=30, verbose_name='Documento')),
                ('type', models.CharField(choices=[('supplier', 'Fornecedor'), ('customer', 'Cliente'), ('both', 'Ambos')], default='both', max_length=20, verbose_name='Tipo')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counterparties', to='participants.participant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
