# Generated by Django 5.2.12 on 2026-03-18 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTransformationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yield_factor', models.DecimalField(decimal_places=6, help_text='Quantidade do produto destino gerada a partir de 1 unidade base do produto origem.', max_digits=14, verbose_name='Fator de rendimento')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Observações')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('source_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transformation_rules_out', to='catalog.product')),
                ('target_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transformation_rules_in', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Regra de transformação',
                'verbose_name_plural': 'Regras de transformação',
                'ordering': ['source_product__name', 'target_product__name'],
                'unique_together': {('source_product', 'target_product')},
            },
        ),
        migrations.CreateModel(
            name='ProductUnitConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_unit', models.CharField(choices=[('m3', 'm³'), ('kg', 'kg'), ('t', 't'), ('un', 'un')], max_length=10, verbose_name='Unidade de origem')),
                ('to_unit', models.CharField(choices=[('m3', 'm³'), ('kg', 'kg'), ('t', 't'), ('un', 'un')], max_length=10, verbose_name='Unidade de destino')),
                ('factor', models.DecimalField(decimal_places=6, help_text='Multiplica a quantidade da unidade de origem para chegar na unidade de destino.', max_digits=14, verbose_name='Fator de conversão')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Observações')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_conversions', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Conversão de unidade',
                'verbose_name_plural': 'Conversões de unidade',
                'ordering': ['product__name', 'from_unit', 'to_unit'],
                'unique_together': {('product', 'from_unit', 'to_unit')},
            },
        ),
    ]
