# Generated by Django 5.2.12 on 2026-03-20 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_producttransformationrule_participant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttransformationrule',
            options={'ordering': ['participant__trade_name', 'participant__legal_name', 'source_product__name', 'target_product__name'], 'verbose_name': 'Regra de transformação', 'verbose_name_plural': 'Regras de transformação'},
        ),
    ]
