# Generated by Django 5.2.12 on 2026-04-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_producttransformationrule_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('m3', 'm³'), ('kg', 'kg'), ('t', 't'), ('un', 'un'), ('mst', 'mst')], max_length=10, verbose_name='Unidade'),
        ),
        migrations.AlterField(
            model_name='productunitconversion',
            name='from_unit',
            field=models.CharField(choices=[('m3', 'm³'), ('kg', 'kg'), ('t', 't'), ('un', 'un'), ('mst', 'mst')], max_length=10, verbose_name='Unidade de origem'),
        ),
        migrations.AlterField(
            model_name='productunitconversion',
            name='to_unit',
            field=models.CharField(choices=[('m3', 'm³'), ('kg', 'kg'), ('t', 't'), ('un', 'un'), ('mst', 'mst')], max_length=10, verbose_name='Unidade de destino'),
        ),
    ]
