# Generated by Django 5.2.12 on 2026-06-22 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participants', '0007_participant_ativo_coc_participant_ativo_fm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da espécie')),
                ('fator_m3_para_ton', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Fator m³ → tonelada')),
                ('fator_m3_para_st', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Fator m³ → st')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especies', to='participants.participant')),
            ],
            options={
                'verbose_name': 'Espécie',
                'verbose_name_plural': 'Espécies',
                'ordering': ['nome'],
                'unique_together': {('participant', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Propriedade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do projeto/propriedade')),
                ('codigo', models.CharField(blank=True, max_length=100, verbose_name='Código/CAR')),
                ('area_hectares', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Área (ha)')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propriedades', to='participants.participant')),
            ],
            options={
                'verbose_name': 'Propriedade',
                'verbose_name_plural': 'Propriedades',
                'ordering': ['nome'],
                'unique_together': {('participant', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='InventarioEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data do inventário')),
                ('documento', models.CharField(blank=True, max_length=100, verbose_name='Documento/Contrato')),
                ('volume', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Volume informado')),
                ('unidade', models.CharField(choices=[('m3', 'm³'), ('ton', 'Tonelada'), ('st', 'Estéreo (st)')], default='m3', max_length=10, verbose_name='Unidade')),
                ('volume_m3', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Volume padronizado (m³)')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='manejo/inventarios/', verbose_name='Anexo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='manejo.especie')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='participants.participant')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='manejo.propriedade')),
            ],
            options={
                'verbose_name': 'Entrada de Inventário',
                'verbose_name_plural': 'Entradas de Inventário',
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SaidaManejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('documento', models.CharField(blank=True, max_length=100, verbose_name='Nº NF')),
                ('cliente_nome', models.CharField(blank=True, max_length=255, verbose_name='Cliente')),
                ('declaracao_fsc', models.BooleanField(default=True, verbose_name='Declaração FSC')),
                ('volume', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Volume informado')),
                ('unidade', models.CharField(choices=[('m3', 'm³'), ('ton', 'Tonelada'), ('st', 'Estéreo (st)')], default='m3', max_length=10, verbose_name='Unidade')),
                ('volume_m3', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Volume padronizado (m³)')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='manejo/saidas/', verbose_name='Anexo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saidas', to='manejo.inventarioentrada')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saidas_manejo', to='participants.participant')),
            ],
            options={
                'verbose_name': 'Saída de Manejo',
                'verbose_name_plural': 'Saídas de Manejo',
                'ordering': ['-data', '-id'],
            },
        ),
    ]
