# Generated by Django 5.2.12 on 2026-06-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ('manejo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriedade',
            name='municipio',
            field=models.CharField(blank=True, max_length=120, verbose_name='Município'),
        ),
        migrations.AddField(
            model_name='propriedade',
            name='uf',
            field=models.CharField(blank=True, max_length=2, verbose_name='UF'),
        ),
    ]
